CREATE TABLE `PROVIDERS` (
  `PROVIDER_ID` VARCHAR(50) PRIMARY KEY,
  `NAME` NVARCHAR(50),
  `PHONE` VARCHAR(15),
  `ADDRESS` NVARCHAR(255),
  `EMAIL` VARCHAR(100),
  `STATUS` NVARCHAR(100)
);

CREATE TABLE `ROLES` (
  `ROLE_ID` VARCHAR(10) PRIMARY KEY,
  `NAME` NVARCHAR(50),
  `DESCRIPTION` NVARCHAR(255)
);

CREATE TABLE `PERMISSION` (
  `PERMISSION_ID` VARCHAR(10) PRIMARY KEY,
  `NAME` NVARCHAR(30),
  `STATUS` NVARCHAR(255)
);

CREATE TABLE `ROLE_PERMISSIONS` (
  `ROLE_ID` VARCHAR(10),
  `PERMISSION_ID` VARCHAR(30),
  `URL` VARCHAR(100),
  `ACTION` VARCHAR(100),
  `STATUS` NVARCHAR(100),
  PRIMARY KEY (`ROLE_ID`, `PERMISSION_ID`)
);

CREATE TABLE `IMPORT` (
  `IMPORT_ID` VARCHAR(10) PRIMARY KEY,
  `PROVIDER_ID` VARCHAR(10),
  `USER_ID` VARCHAR(10),
  `DATE_CREATE` DATE,
  `TOTAL` FLOAT
);

CREATE TABLE `BRANDS` (
  `BRAND_ID` VARCHAR(10) PRIMARY KEY,
  `NAME` NVARCHAR(50),
  `IMG` NVARCHAR(255),
  `STATUS` NVARCHAR(100)
);

CREATE TABLE `PRODUCTS` (
  `PRODUCT_ID` VARCHAR(10) PRIMARY KEY,
  `BRAND_ID` VARCHAR(10),
  `CATEGORY_ID` VARCHAR(10),
  `NAME` NVARCHAR(50),
  `IMG` NVARCHAR(255),
  `PRICE` FLOAT,
  `QUANTITY` INT,
  `STATUS` NVARCHAR(100)
);

CREATE TABLE `DISCOUNTS` (
  `DISCOUNT_ID` VARCHAR(10) PRIMARY KEY,
  `NAME` NVARCHAR(50),
  `CONDITION` VARCHAR(50),
  `START_DATE` DATE,
  `END_DATE` DATE,
  `PERCENT` FLOAT
);

CREATE TABLE `IMPORT_DEATAIL` (
  `PRODUCT_ID` VARCHAR(10),
  `IMPORT_ID` VARCHAR(10),
  `UNIT_PRICE` FLOAT,
  `QUANTITY` INT,
  PRIMARY KEY (`IMPORT_ID`, `PRODUCT_ID`)
);

CREATE TABLE `EXPORT` (
  `EXPORT_ID` VARCHAR(10) PRIMARY KEY,
  `DISCOUNT_ID` VARCHAR(10),
  `EMPLOYEE_ID` VARCHAR(10),
  `CUSTOMER_ID` VARCHAR(10),
  `DATE_CREATE` DATE,
  `TOTAL` FLOAT,
  `STATUS` NVARCHAR(100)
);

CREATE TABLE `EXPORT_DEATAIL` (
  `EXPORT_ID` VARCHAR(10),
  `PRODUCT_ID` VARCHAR(10),
  `UNIT_PRICE` FLOAT,
  `QUANTITY` INT,
  PRIMARY KEY (`EXPORT_ID`, `PRODUCT_ID`)
);

CREATE TABLE `ACCOUNTS` (
  `USERNAME` varchar(10) PRIMARY KEY,
  `PASSWORD` varchar(10),
  `ROLE_ID` varchar(10),
  `DATE_CREATE` DATE,
  `ID` varchar(10),
  `STATUS` varchar(50)
);

CREATE TABLE `CATEGORY` (
  `CATEGORY_ID` varchar(10) PRIMARY KEY,
  `NAME` varchar(100),
  `STATUS` VARCHAR(100)
);

CREATE TABLE `USERS` (
  `USER_ID` VARCHAR(20) PRIMARY KEY,
  `TYPE_USER_ID` VARCHAR(20),
  `NAME` NVARCHAR(50),
  `PHONE` VARCHAR(10),
  `ADDRESS` NVARCHAR(255),
  `EMAIL` VARCHAR(100),
  `STATUS` NVARCHAR(100)
);

CREATE TABLE `TYPE_USERS` (
  `TYPE_USER_ID` VARCHAR(10) PRIMARY KEY,
  `NAME` NVARCHAR(50),
  `STATUS` NVARCHAR(100)
);

ALTER TABLE `USERS` ADD CONSTRAINT `TYPE_USER_ID_FK` FOREIGN KEY (`TYPE_USER_ID`) REFERENCES `TYPE_USERS` (`TYPE_USER_ID`);

ALTER TABLE `PRODUCTS` ADD CONSTRAINT `CATEGORY_ID_FK` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`CATEGORY_ID`);

ALTER TABLE `ROLE_PERMISSIONS` ADD CONSTRAINT `ROLE_FK` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLES` (`ROLE_ID`);

ALTER TABLE `ROLE_PERMISSIONS` ADD CONSTRAINT `PERMISSION_ID_FK` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `PERMISSION` (`PERMISSION_ID`);

ALTER TABLE `IMPORT` ADD CONSTRAINT `PROVIDER_ID_FK` FOREIGN KEY (`PROVIDER_ID`) REFERENCES `PROVIDERS` (`PROVIDER_ID`);

ALTER TABLE `IMPORT` ADD CONSTRAINT `USER_ID_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

ALTER TABLE `PRODUCTS` ADD CONSTRAINT `BRAND_ID_FK` FOREIGN KEY (`BRAND_ID`) REFERENCES `BRANDS` (`BRAND_ID`);

ALTER TABLE `IMPORT_DEATAIL` ADD CONSTRAINT `PRODUCT_ID_FK` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`);

ALTER TABLE `IMPORT_DEATAIL` ADD CONSTRAINT `IMPORT_ID_FK` FOREIGN KEY (`IMPORT_ID`) REFERENCES `IMPORT` (`IMPORT_ID`);

ALTER TABLE `EXPORT` ADD CONSTRAINT `USER_ID_FK` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `USERS` (`USER_ID`);

ALTER TABLE `EXPORT` ADD CONSTRAINT `USER_ID_FK` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `USERS` (`USER_ID`);

ALTER TABLE `EXPORT` ADD CONSTRAINT `DISCOUNT_ID_FK` FOREIGN KEY (`DISCOUNT_ID`) REFERENCES `DISCOUNTS` (`DISCOUNT_ID`);

ALTER TABLE `EXPORT_DEATAIL` ADD CONSTRAINT `PRODUCT_ID_FK` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`);

ALTER TABLE `EXPORT_DEATAIL` ADD CONSTRAINT `EXPORT_ID_FK` FOREIGN KEY (`EXPORT_ID`) REFERENCES `EXPORT` (`EXPORT_ID`);

ALTER TABLE `ACCOUNTS` ADD CONSTRAINT `USERNAME_FK` FOREIGN KEY (`USERNAME`) REFERENCES `USERS` (`USER_ID`);

ALTER TABLE `ACCOUNTS` ADD CONSTRAINT `ROLE_ID_FK` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLES` (`ROLE_ID`);
